source("scripts/input.R")
source("scripts/tc.R")

png("figuras/barplots-metastase.png", width = 700, height = 700)
par(mfrow = c(2,2))
t <- met.sex; barplot(t, legend.text = (rownames(t)), beside = T, col = rainbow(length((rownames(t))), .7, .7), main = "Metástase por Sexo", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t)$p.value, eps = .001, digits = 2)), ylab = "Número de pacientes")
t <- met.hist; barplot(t, legend.text =  (rownames(t)), beside = T, col = rainbow(length((rownames(t))), .7, .7), main = "Metástase por Tipo histológico", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t)$p.value, eps = .001, digits = 2)), ylab = "Número de pacientes")
t <- met.obt; barplot(t, legend.text =  (rownames(t)), beside = T, col = rainbow(length((rownames(t))), .7, .7), main = "Metástase por Óbito", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t)$p.value, eps = .001, digits = 2)), ylab = "Número de pacientes")
t <- met.cir; barplot(t, legend.text =  (rownames(t)), beside = T, col = rainbow(length((rownames(t))), .7, .7), main = "Metástase por Tipo de cirurgia", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t)$p.value, eps = .001, digits = 2)), ylab = "Número de pacientes")
rm(t)
dev.off()

png("figuras/bp-obitos_hist.png", width = 700, height = 700)
t <- obt.hist; barplot(t, beside = T, legend.text = rownames(t), col = rainbow(length((rownames(t))), .7, .7), main = "Óbito por Tipo histológico", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t)$p.value, eps = .001, digits = 2)), ylab = "Número de pacientes")
rm(t)
dev.off()

png("figuras/bp-obitos_met.png", 700, 700)
t <- obt.met; barplot(t, legend.text =  (rownames(t)), beside = T, main = "Óbito por presença de metástase", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t)$p.value, eps = .001, digits = 2)), col = rainbow(length((rownames(t))), .7, .7), ylab = "Número de pacientes")
dev.off()

png("figuras/bp-obitos_estad.png", 700, 700)
t <- obt.est; barplot(t, legend.text =  (rownames(t)), beside = T, main = "Óbito por Estadiamento", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t)$p.value, eps = .001, digits = 2)), col = rainbow(length((rownames(t))), .7, .7), ylab = "Número de pacientes")
dev.off()

png("figuras/bp-obitos_cir.png", width = 700, height = 700)
t <- obt.cir; barplot(t, beside = T, legend.text = rownames(t), col = rainbow(length((rownames(t))), .7, .7), main = "Óbito por Tipo de cirurgia", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t)$p.value, eps = .001, digits = 2)), ylab = "Número de pacientes")
rm(t)
dev.off()

png("figuras/barplots-estadiamento.png", width = 700, height = 700)
par(mfrow = c(2,2))
t <- est.sex; barplot(t, legend.text = (rownames(t)), beside = T, main = "Estadiamento por Sexo", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t)$p.value, eps = .001, digits = 2)), col = rainbow(length((rownames(t))), .7, .7), ylab = "Número de pacientes")
t <- est.hist; barplot(t, legend.text =  (rownames(t)), beside = T, main = "Estadiamento por Tipo histológico", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t, workspace = 2e+6)$p.value, eps = .001, digits = 2)), col = rainbow(length((rownames(t))), .7, .7), ylab = "Número de pacientes")
t <- est.obt; barplot(t, legend.text =  (rownames(t)), beside = T, main = "Estadiamento por Óbito", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t)$p.value, eps = .001, digits = 2)), col = rainbow(length((rownames(t))), .7, .7), ylab = "Número de pacientes")
t <- est.cir; barplot(t, legend.text =  (rownames(t)), beside = T, main = "Estadiamento por Tipo de cirurgia", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t)$p.value, eps = .001, digits = 2)), col = rainbow(length((rownames(t))), .7, .7), ylab = "Número de pacientes")
rm(t)
dev.off()

png("figuras/barplots-tipo_tempo.png", width = 700, height = 700)
t <- tip.tmp; barplot(t, legend.text =  (rownames(t)), beside = T, main = "Tempo de Diagnóstico", args.legend = list(title = names(dimnames(t))[1]), xlab = paste("p-valor:", format.pval(fisher.test(t, workspace = 2e+6)$p.value, eps = .001, digits = 2)), col = rainbow(length((rownames(t))), .7, .7), ylab = "Número de pacientes")
rm(t)
dev.off()

rm(met.sex, met.hist, met.obt, met.cir)
rm(obt.sex, obt.hist, obt.met, obt.cir)
rm(est.sex, est.hist, est.obt, est.cir)
rm(tip.tmp)
source("scripts/cleanup.R")
